package massmailer;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author spidy
 * 
 * This class displays the user interface to input the needed data, the username, password etc.
 * Also saves the data entered by the user
 * 
 */
public class UserInputInterfaceGui extends javax.swing.JFrame {

    static volatile boolean userInputWindow_closed=false;
    /**
     *
     */
    public UserInputInterfaceGui() {
        
        initComponents();
        setVisible(true);
        setTitle("MASS MAILER");
        set_default_display();
        addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e){
            userInputWindow_closed=true;
            System.exit(0);
        }
        });
    }
    
    /**
     * This method sets the default values in the text fields
     * 
     */
    void set_default_display()
    {
        port_Input.setText(String.valueOf(UserInputAndDefaulValues.port));
        host_smtp_Input.setText(UserInputAndDefaulValues.host_smtp);
        mailer_username_Input.setText(UserInputAndDefaulValues.mailerUsername);
        mailer_password_Input.setText(UserInputAndDefaulValues.mailerPassword);
        database_username_Input.setText(UserInputAndDefaulValues.databaseUsername);
        database_password_Input.setText(UserInputAndDefaulValues.databasePassword);
        database_url_Input.setText(UserInputAndDefaulValues.database_url);
        database_table_name_Input.setText(UserInputAndDefaulValues.database_table_name);
    }
    /**
     * This methods gets the user input from the text fields
     */
    void get_user_input()
    {
        UserInputAndDefaulValues.port = Integer.parseInt(port_Input.getText());
        UserInputAndDefaulValues.host_smtp = host_smtp_Input.getText();
        UserInputAndDefaulValues.mailerUsername = mailer_username_Input.getText();
        UserInputAndDefaulValues.mailerPassword = mailer_password_Input.getText();
        UserInputAndDefaulValues.databaseUsername = database_username_Input.getText();
        UserInputAndDefaulValues.databasePassword = database_password_Input.getText();
        UserInputAndDefaulValues.database_url = database_url_Input.getText();
        UserInputAndDefaulValues.database_table_name = database_table_name_Input.getText();
        UserInputAndDefaulValues.no_of_mails_per_query =  Integer.parseInt(no_of_mails_to_fetch.getText());   
     }
    /*
     * This methods writes the user filled data to the default file if the user wishes so
     */
   void write_to_defaultInputs_file()
   {
        
        try {
            String currentPath=System.getProperty("user.dir")+File.separator+"defaultInputs.txt";
            File file = new File(currentPath);
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            BufferedWriter writer = new BufferedWriter(fw);
            writer.write(String.valueOf(UserInputAndDefaulValues.port));
            writer.newLine();
            writer.write(UserInputAndDefaulValues.host_smtp);
            writer.newLine();
            writer.write(UserInputAndDefaulValues.mailerUsername);
            writer.newLine();
            writer.write(UserInputAndDefaulValues.mailerPassword);
            writer.newLine();
            writer.write(UserInputAndDefaulValues.databaseUsername);
            writer.newLine();
            writer.write(UserInputAndDefaulValues.databasePassword);
            writer.newLine();
            writer.write(UserInputAndDefaulValues.database_url);
            writer.newLine();
            writer.write(UserInputAndDefaulValues.database_table_name);
            writer.newLine();
            writer.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(UserInputInterfaceGui.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            
        }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        port_Input = new javax.swing.JTextField();
        host_smtp_Input = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        mailer_username_Input = new javax.swing.JTextField();
        mailer_password_Input = new javax.swing.JPasswordField();
        database_password_Input = new javax.swing.JPasswordField();
        database_username_Input = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        database_url_Input = new javax.swing.JTextField();
        start_mailing_Button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        database_table_name_Input = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        set_defaultInputs_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        no_of_mails_to_fetch = new javax.swing.JTextField();
        setMessageButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Port");

        jLabel2.setText("Host_smtp");

        jLabel3.setText("Mailer_Username");

        jLabel4.setText("Mailer_Password");

        port_Input.setText("port_Input");

        host_smtp_Input.setText("host_smtp_Input");

        jLabel7.setText("Database_password");

        mailer_username_Input.setText("mailer_username_Input");
        mailer_username_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailer_username_InputActionPerformed(evt);
            }
        });

        mailer_password_Input.setText("jPasswordField1");

        database_password_Input.setText("jPasswordField2");

        database_username_Input.setText("database_username_Input");

        jLabel5.setText("Database_url");

        database_url_Input.setText("jdbc:mysql://127.0.0.1/addressbook");

        start_mailing_Button.setText("START MAILING");
        start_mailing_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_mailing_ButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INPUT REQUIRED");

        jLabel9.setText("Database_table_name");

        database_table_name_Input.setText("database_table_Input");

        jLabel10.setText("Database_username");

        set_defaultInputs_Button.setText("SET DEFAULT INPUTS");
        set_defaultInputs_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_defaultInputs_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("No. of emails to be fetched");

        no_of_mails_to_fetch.setText("100");

        setMessageButton.setText("Set Message");
        setMessageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setMessageButtonMouseClicked(evt);
            }
        });

        jLabel11.setText("Click Set Message to set Message");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(start_mailing_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(set_defaultInputs_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(database_url_Input)
                            .addComponent(database_password_Input)
                            .addComponent(database_username_Input)
                            .addComponent(mailer_password_Input)
                            .addComponent(mailer_username_Input)
                            .addComponent(host_smtp_Input)
                            .addComponent(port_Input)
                            .addComponent(database_table_name_Input)
                            .addComponent(no_of_mails_to_fetch)
                            .addComponent(setMessageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(port_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(host_smtp_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mailer_username_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailer_password_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(database_username_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(database_password_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(database_url_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(database_table_name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(no_of_mails_to_fetch)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setMessageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start_mailing_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set_defaultInputs_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
 * This method performs the start_mailing_ButtonActionPerformed and checks if message is set or not
 */
    private void start_mailing_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_mailing_ButtonActionPerformed
            get_user_input();
          if(UserInputAndDefaulValues.subject.equals("not set, default subject"))
                JOptionPane.showMessageDialog(this, "Subject Not Set.");
          else if(UserInputAndDefaulValues.message_body.equals("not set. This is a default Message"))
                JOptionPane.showMessageDialog(this, "Message Body Not Set.");
          else
          {
                UserInputAndDefaulValues.start_mailing_flag=true;
               // new MailInProgressGui();
                setVisible(false);
                dispose();
          }
         
    }//GEN-LAST:event_start_mailing_ButtonActionPerformed

    private void mailer_username_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailer_username_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailer_username_InputActionPerformed

    private void set_defaultInputs_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_defaultInputs_ButtonActionPerformed
            get_user_input();
            write_to_defaultInputs_file();
    }//GEN-LAST:event_set_defaultInputs_ButtonActionPerformed

    private void setMessageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setMessageButtonMouseClicked
        // TODO add your handling code here:
        new MessageInputGui();
        
    }//GEN-LAST:event_setMessageButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInputInterfaceGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInputInterfaceGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInputInterfaceGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInputInterfaceGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInputInterfaceGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField database_password_Input;
    private javax.swing.JTextField database_table_name_Input;
    private javax.swing.JTextField database_url_Input;
    private javax.swing.JTextField database_username_Input;
    private javax.swing.JTextField host_smtp_Input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField mailer_password_Input;
    private javax.swing.JTextField mailer_username_Input;
    private javax.swing.JTextField no_of_mails_to_fetch;
    private javax.swing.JTextField port_Input;
    private javax.swing.JButton setMessageButton;
    private javax.swing.JButton set_defaultInputs_Button;
    private javax.swing.JButton start_mailing_Button;
    // End of variables declaration//GEN-END:variables
}
